#
# Configuration for ACI Fabric
#
aci_config:
  apic_hosts:
    - 10.30.120.100             # List of APIC hosts to connect for APIC API
  vrf:                          # VRF used to create all kubernetes EPs
    name: mykube-vrf
    tenant: common              # This can be system-id or common

  cluster_l3out:
    name: calico_l3out          # This is the l3out created by acc-provision
    aep: kube-cluster             # Required field. The AEP for ports/VPCs used by this cluster
    svi:
      type: floating                          # This is the interface type. Only "floating" is supported
      floating_ip: 2.100.101.100/24           # Required field. Should be an IP in the node subnet
      secondary_ip: 2.100.101.254/24          # Required field
      vlan_id: 13                             # Required field. Valid vlan-id for the whole cluster
      mtu: 9000                               # 9000 is the recommended value.
    bgp:
      secret: test                  # BGP password for the peerings generated by BGPPeer resource
      peering:
        prefixes: 500               # Maximum number of prefixes to limit how many prefixes we can accept from a single K8s node. Default is 500
        remote_as_number: 64512     # By default, all Calico nodes use 64512 AS number
        aci_as_number: 2            # Required field. This is derived frm APIC.

  l3out:
    name: mykube_l3out          # External l3Out
    external_networks:
    - mykube_extepg             # Used for external contracts

#
# Networks used by ACI containers
#
net_config:
  node_subnet: 2.100.101.0/24       # Subnet to use for nodes
  pod_subnet: 20.2.0.0/16           # Subnet to use for Kubernetes Pods
  extern_dynamic: 20.3.0.0/16       # Subnet to use for Service External IPs and Service LoadBalancer IPs to be advertised over BGP.
  cluster_svc_subnet: 10.96.0.0/12  # Subnet to use for Kubernetes Service Cluster IPs to be advertised over BGP
  # advertise_cluster_svc_subnet: false # Do not advertise cluster ip subnet
#
# Configuration for calico networking
#
calico_config:
  net_config: {}
    # block_size: 20            # IPAM IPV4 block size. Valid values are 20-32(inclusive). Default value is 26.
                                # Updating the block size on an already installed cluster is not supported.

# Calico node rack association
# Required config
topology:
  rack:                         # Each rack has a pair of ToR leaf switches and Kubernetes nodes
  - id: 1                       # "id" of a ToR, and is user assigned.
    aci_pod_id: 1
    leaf:                       # User should only provide anchor nodes in the input file
    - id: 101                   # Node id of anchor nodes
      local_ip: 2.100.101.201   # The IP address of the peer
    - id: 102
      local_ip: 2.100.101.202
    node:  
    - name: k8s-node1           # K8s nodes
    - name: k8s-node2
  - id: 2
    aci_pod_id: 1
    leaf:
    - id: 103
      local_ip: 2.100.101.203
    node:  
    - name: k8s-node3
    - name: k8s-node4
