#
# Configuration for ACI Fabric
#
aci_config:
  apic_hosts:                   # List of APIC hosts to connect for APIC API
  - 10.1.1.101

#
# Configuration for container registry
# Update if a custom container registry has been setup
#
registry:
  image_prefix: noiro                   # e.g: registry.example.com/noiro
  # image_pull_secret: secret_name      # (if needed)
  # use_digest: true   # option to pull images using digest, override if needed, default is false.

# kube_config:
    # image_pull_policy: Always            # Image pull policy for ACI CNI components, default is IfNotPresent

vmm_lite_config:                                                     # Contains VMM lite specific configurations
  aaep_monitoring_enabled: True                                      # default is False
  bridge_name: "br-nad"                                              # Name of linux bridge from worker nodes, needs to be created with same name on all worker nodes
  cno_identifier: "cno-id1"                                          # Prefix for EPG annotation to identify CNO, default is "cno"
  bridge_nad_config_file: "bridge_nad_config.yaml"                   # Path to bridge NAD config file (must be a YAML file with a top-level mapping/dictionary), needs to be created with proper config with optional fields
  kubeapi_vlan: 4001                                                 # The VLAN used by the physdom for nodes (Kubernetes only)
  apic_username: "admin"                                             # APIC username

